---
server:
  port: 8761
 
eureka:
  instance:
    preferIpAddress: true
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  server:
    waitTimeInMsWhenSyncEmpty: 0
  
logging:
  level:
    com.netflix: 'WARN'
    org.springframework.cloud: 'WARN'
